# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:1077444234645:android:3ff53b6d1ae3c2caadba9c",
    firebase_cli_token:"1//03C9t_kAzcxKNCgYIARAAGAMSNwF-L9IrC_CiIVAwLljLbKe6OO088iHyDEsRXrk2g8on9rxey60c31LVZrKRU0pzsAAIw0nAK0M",
    android_artifact_type: "APK",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "ya9951638@gmail.com",
    release_notes:"First FastLane Release For Firebase App Distribution"
  )
  end
end
